# -----------------------------------------------------------------------------
# ALS SuStaIn model configuration (14 pre-selected regional DBM W-scores)
#
# Notes:
# - This file is NOT intended to be modified at runtime.
# - This config fully defines the preprocessing chain for model input.
# - Feature order, selection, and sign conventions are fixed from training.
# - Paths are relative to the project root directory.
# -----------------------------------------------------------------------------

version: "1.0.0"
display_name: ALS SuStaIn (14 ROI DBM W-scores) + Survival Ensemble ('dpr' + sustain subtype and stage interaction term)

# --- MODELS METADATA ---
models:
  sustain_model:
    model_id: CALSNIC_sustain_14_reg_dbm_wscore
    model_type: zscore
    model_nb_subtype: 3
    model_file: models/sustain/CALSNIC_sustain_14_reg_dbm_wscore.joblib
    model_meta_file: models/sustain/CALSNIC_sustain_14_reg_dbm_wscore.pickle
  
  survival_ensemble_model:
    model_id: CALSNIC_coxnet_bootstrap_ensemble
    model_type: coxnet_bootstrap_100
    model_file: models/coxnet/CALSNIC_coxnet_dprAndSustainInteractionfeatures_bootstrap_ensemble_model.joblib
    reference_library: models/coxnet/CALSNIC_coxnet_dprAndSustainInteractionfeatures_bootstrap_references_curves.joblib
    # Explicitly list non-sustain features (like DPR) needed for Coxnet
    clinical_features: [dpr]

# Accepted inputs for pipeline execution
processing_input_accepted:
  - t1w_maps
  - dbm_maps
  - regional_dbm
  - regional_dbm_wscores

# Preprocessing steps to convert input into model-ready features
processing_chain:

  - step: dbm_generation
    input_accepted: [t1w_maps]
    output_type: dbm_maps
    
  - step: roi_extraction
    input_accepted: [dbm_maps]
    output_type: regional_dbm
    result_prefix: 'dbm_'
    # Atlases used in ROI extraction
    atlases:
        - jhu25       # Core atlas required for model input
        - cerebra     # Core atlas required for model input
        - allen       # Can be added for extra ROI averages
        - handknob    # Can be added for extra ROI averages
    remove_sulci: true # Whether we exclude the sulci from the ROI avr computation
    csf_threshold: 0.2 # The csf threshold above what it is considered as sulci.

  - step: w_score_normalization
    input_accepted: [regional_dbm]
    output_type: regional_dbm_wscores
    # Healthy control cohort reference for W-score computation
    model_artifact: models/hc_lme/CALSNIC_wscore_hc_cohort.joblib

  - step: sustain_inference
    input_accepted: [regional_dbm_wscores]
    output_type: sustain_assignments # ml_subtype, ml_stage and (onehot_subtype x stage) interaction terms
    # Exact list and order of features used during training
    # Changing these without retraining invalidates the model
    regions_list:
      - dbm_cerebra_w_precentral
      - dbm_cerebra_w_paracentral
      - dbm_jhu25_w_corticospinal_tract
      - dbm_cerebra_w_brainstem
      - dbm_cerebra_w_superiorfrontal
      - dbm_cerebra_w_rostralmiddlefrontal
      - dbm_cerebra_w_superiorparietal
      - dbm_cerebra_w_inferiorparietal
      - dbm_cerebra_w_caudate
      - dbm_cerebra_w_putamen
      - dbm_cerebra_w_amygdala
      - dbm_cerebra_w_hippocampus
      - dbm_cerebra_w_entorhinal
      - dbm_cerebra_w_parahippocampal
    # Logic: Flip to have positive as "presence" of pathology
    standardize_to_positive_pathology: true
    # None are excluded as each region in the list is expected to be atrophied (or stable) in ALS
    exclude_from_inversion: []

  - step: survival_prediction
    input_accepted: [sustain_assignments]
    output_type: survival_mean_curve_info
    # DPR (disease progression rate) + (onehot_subtype x stage) interaction terms are the features used for Coxnet prediction
    features_list: ['dpr', 'S1_x_stage', 'S2_x_stage', 'S3_x_stage'] 
    period_window: 60 # Number of months to predict survival over (e.g., 5 years)
    #Result: Mean curve + 95% CI (via the bootstrap ensemble)
    prediction_type: bootstrap_ensemble_inference

notes: >
  Steps are executed based on input type, ensuring reproducibility of training-time feature representation.
  Optional atlases may be added for extra ROI analyses, but mandatory atlases must always be present.
