# Container-internal resources (do not change at runtime)

paths:
  masks:
    brain: resources/masks/mni_icbm152_t1_tal_nlin_sym_09c_mask.nii
    csf_prob: resources/masks/mni_icbm152_csf_tal_nlin_sym_09c.nii

  atlases:
    allen: resources/atlases/atlas_Allen_mni_icbm152_t1_tal_nlin_sym_09b_labels.nii
    cerebra: resources/atlases/atlas_CerebrA_mni_icbm152_tal_nlin_sym_09c.nii
    jhu50: resources/atlases/atlas_JHU-ICBM-tracts-maxprob-thr50-1mm-sym.nii.gz
    handknob: resources/atlases/Hand_Knob_ROIs_xm34_ym22_z54_spherical_9mm_gm02_gm_and_wm_wocsf.nii.gz

  atlases_info:
    allen: resources/atlases/atlas_Allen_mni_icbm152_t1_tal_nlin_sym_09b_labels_info.csv
    cerebra: resources/atlases/atlas_CerebrA_mni_icbm152_tal_nlin_sym_09c_info.csv
    jhu50: resources/atlases/atlas_JHU-ICBM-tracts-maxprob-thr50-1mm-sym_info.csv
    handknob: resources/atlases/Hand_Knob_ROIs_xm34_ym22_z54_spherical_9mm_gm02_gm_and_wm_wocsf_info.csv

indices:
  ventricles:
    - 119
    - 1119
    - 57
    - 1057
    - 58
    - 1058
    - 59
    - 1059
    - 60
    - 1060
    - 61
    - 1061
    - 141
    - 1141
    - 129
    - 1129
    - 130
    - 1130
